// DOM contract test with synthetic network responses; not a browser/rendering test.
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync(path.join(__dirname,'../../src/sera/demo/static/index.html'),'utf8');
const scenario={region_id:'test-region',name:'Synthetic UI test',asset_label:'<img src=x onerror=alert(1)>',event_context:'Test only',longitude:0,latitude:0,indices:['NDWI','NBR'],before:{start:'2022-01-01',end:'2022-01-10'},after:{start:'2022-01-11',end:'2022-01-20'}};
const evidence={evidence_id:'asset_buffer-ndwi',scope:'asset_buffer',index:'NDWI',before:-.2,after:.3,delta_after_minus_before:.5,usable_area_fraction:.9,history:[{year:2020,mean:-.3}],z_score:null};
const record={status:'complete',stage:'complete',retryable:false,config:scenario,result:{packet:{evidence:[evidence],as_of:'2022-01-20',limitations:['Synthetic fixture'],data_gaps:[],sources:['https://example.org'],source_manifest:{}},bounds:[-1,-1,1,1],previews:['before','after'],map:{features:[{geometry:{type:'Polygon',coordinates:[[[-1,-1],[1,-1],[1,1],[-1,-1]]]},properties:{h3_cell:'test-cell',NDWI_delta:.5,NDWI_coverage:.9}}]},generation:{provider:'test',model:'test-model',adk_version:'2.9.2',report:{observations:[{text:'Test change',evidence_ids:['asset_buffer-ndwi']}],interpretation:'Fixture',review_action:'Review',limitations:[]}}}};
const calls=[];const errors=[];
const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'dangerously',beforeParse(w){w.fetch=async(url,opts={})=>{calls.push([url,opts.method]);let data;if(url.endsWith('/scenarios'))data=[scenario,...['other','gyirong-fixture','assam-fixture'].map(id=>({...scenario,region_id:id,name:id}))];else if(url.endsWith('/regions'))data=scenario;else if(url.endsWith('/scans'))data={scan_id:'demo_'+'a'.repeat(32)};else data=record;return{ok:true,json:async()=>data};};w.addEventListener('error',e=>errors.push(e.message));}});
async function flush(){await new Promise(resolve=>setTimeout(resolve,30));}
(async()=>{await flush();const d=dom.window.document;assert.equal(d.querySelectorAll('#scenario option').length,4);assert.equal(d.querySelector('#asset img'),null);assert(d.getElementById('asset').textContent.includes('<img'));d.getElementById('scenario').value='assam-fixture';d.getElementById('scenario').dispatchEvent(new dom.window.Event('change'));assert.equal(JSON.parse(d.getElementById('config').value).region_id,'assam-fixture');d.getElementById('start').click();await flush();assert.equal(d.getElementById('result').style.display,'block');assert.equal(d.querySelectorAll('#map polygon').length,1);assert.equal(d.querySelectorAll('#measurements tr').length,1);assert(d.getElementById('report').textContent.includes('Test change'));assert(d.getElementById('export').href.includes('/export'));assert.equal(d.getElementById('error').textContent,'');assert.equal(errors.length,0);assert(calls.some(([u,m])=>u.endsWith('/regions')&&m==='POST'));assert(calls.some(([u,m])=>u.endsWith('/scans')&&m==='POST'));dom.window.close();console.log('PASS: scenario selection, submit, poll, map, table, report, export and safe text rendering');})().catch(e=>{dom.window.close();console.error(e);process.exit(1);});
